[package]
name = "Lecturn"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }
reqwest = "0.12.5"
tokio = { version = "1.38.1", features = ["rt-multi-thread", "macros"] }
bytes = "1.6.1"