[package]
name = "Lecturn"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.132"
serde = { version = "1.0.214", features = ["derive"] }
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
bytes = "1.8.0"
config = "0.14.0"